### ISSUE TITLE
registry.txt url not found

### ISSUE THREAD

**Issue by jntp** [NCAR/GeoCAT#17]
Hello! I've been able to run python code on GeoCAT (on miniconda) fine until yesterday. However, for some reason, I now get an answer message that says:

> Updating file 'registry.txt' from 'https://github.com/NCAR/GeoCAT-datafiles/raw/master/registry.txt' to '/home/jntp/.cache/geocat'.
Traceback (most recent call last):
  File "lum_polar_cln_dff.py", line 6, in <module>
    import geocat.datafiles as gdf
  File "/home/jntp/miniconda3/envs/geocat/lib/python3.7/site-packages/geocat/datafiles/__init__.py", line 28, in <module>
    _update_registry(POOCH)
  File "/home/jntp/miniconda3/envs/geocat/lib/python3.7/site-packages/geocat/datafiles/__init__.py", line 21, in _update_registry
    p.load_registry(p.fetch("registry.txt"))
  File "/home/jntp/miniconda3/envs/geocat/lib/python3.7/site-packages/pooch/core.py", line 545, in fetch
    retry_if_failed=self.retry_if_failed,
  File "/home/jntp/miniconda3/envs/geocat/lib/python3.7/site-packages/pooch/core.py", line 724, in stream_download
    downloader(url, tmp, pooch)
  File "/home/jntp/miniconda3/envs/geocat/lib/python3.7/site-packages/pooch/downloaders.py", line 180, in __call__
    response.raise_for_status()
  File "/home/jntp/miniconda3/envs/geocat/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/NCAR/GeoCAT-datafiles/raw/master/registry.txt

I was wondering what could the issue be here? I believe that the url for registry.txt is now missing? Thanks!

**Comment by michaelavs** [comment]
Hi!

Recently we renamed our 'master' branch to 'main' to promote inclusivity with the language used in the GeoCAT GitHub repositories. This is what is causing your error as the branches/environment will need to be reset to pull from 'main' instead of 'master'. One way to reset and overcome the issue is to first make sure you have set your local branches to track `origin/main` by using: 
```
git branch -m master main
git fetch origin
git branch -u origin/main main 
```

Then try running your code again. 
Edit: @anissa111 pointed out to me, you may want to try to update your geocat-datafiles version from v0.2 (pre-branch name update) to v2021.01.01 (post-branch name update). This should be the more straight forward method for updating/resolving, but if that doesn't work then try the next method.

If the issue persists, you will most likely need to delete your geocat-examples environment and then recreate it. If you are still having this issue after recreating your geocat-examples environment, let us know and we can continue to troubleshoot!

**Comment by jntp** [comment]
I just deleted my geocat-examples environment and recreated it. It now works. Thanks!
